### ISSUE TITLE
Question about PDBBind2016 docked poses

### ISSUE THREAD

**Issue by hnisonoff** [gnina/models#17]
In the README I see the following description:
`<PDBid>_docked.sdf              -- smina docked pose of *_uff.sdf into its cognate receptor.`

Does this mean the re-docking was done by initializing the monte-carlo search at a minimized version of the crystal pose? I had thought that docking would have been initialized at a random conformation such as:
`<PDBid>_conf.sdf                -- RDkit generated conformer from the ligand SMILES.`

**Comment by dkoes** [comment]
Docking always randomizes torsions - it is not influenced by the torsion values of the initial conformer.  However, the bond angles and lengths are kept constant and these can have a significant impact on the docking result (it is important to have a quality conformer).  Using the crystal conformation will yield the best result, but isn't a meaningful result since it requires you know the right answer.  The UFF minimized conformer converts the crystal pose into something that is at a UFF minimum and therefore is possible to be sampled by rdkit's conformer generation while the rdkit generated one yields what is actually sampled.

**Comment by hnisonoff** [comment]
Thank you very much for the thorough clarification. I had thought that even though torsions are sampled, that there may be some bias from initializing with the right torsions. It sounds like for the internals of Gnina and most docking programs that this is not the case though. Really appreciate the help!
