### ISSUE TITLE
ChEMBL and MUV data from JCIM 2017 paper

### ISSUE THREAD

**Issue by agamemnonc** [gnina/models#4]
Hi there, thanks for making available all these resources.  I was wondering whether you have made available the independent virtual screening test sets used in "Protein-Ligand Scoring with Convolutional Neural Networks" (JCIM, 2017), as well as the scores produced by each of the five methods in the benchmark (DUD-E, 2:1, Vina, RF-score, NNScore).

Thanks!

**Comment by dkoes** [comment]
The ChEMBL structures are here: http://bits.csb.pitt.edu/files/chembl_compounds.tar.gz
The MUV structures are here: http://bits.csb.pitt.edu/files/muv_compounds.tar.gz
CNN score output (with a jupyter notebook for making figures) is here: http://bits.csb.pitt.edu/files/cnn2017_scores.tgz
RF/NNscores for DUDe are here: http://bits.csb.pitt.edu/files/rfnn_dude_scores.tgz

I'm going to need @Jsunseri  to point me to where MUV scores are since she assembled that dataset.

I would encourage you to also evaluate the default CNN scoring of gnina 1.0, which should improve on these results from 2017.  Also, care should always be taken when evaluating machine learning methods on DUDe:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220113
https://pubs.acs.org/doi/abs/10.1021/acs.jcim.8b00712

**Comment by agamemnonc** [comment]
Thank you so much @dkoes for the swift reply and for the pointers to Gnina 1.0 release. 

Also thanks for the suggestion regarding DUD-E. We are aware of the inherent biases in the dataset. We are currently using it only as an independent dataset to assess performance of models trained on data from PDBBind (similarly to your 2017 paper where you evaluated models trained on DUD-E on ChEMBL and MUV datasets).

We would be really keen to benchmark our method against Gnina. However, given the very large number of decoys in DUD-E, it would be infeasible for us (in terms of required computational resources) to perform virtual screening on DUD-E using Gnina. Have you by any chance already performed such a screening on DUD-E and made the results available? 

Unfortunately, due to the nature of our models, the CrossDocked dataset (2020 paper) is not appropriate for our case.

Once again, thanks very much for the help and for making everything open and accessible.

P.S. I couldn't help but comment on the excellent choice of username and its relation to your area of research :)

**Comment by dkoes** [comment]
We have a bunch of virtual screening data (both DUDE and LIT-PCBA) and are working on a paper.  @Jsunseri can provide this.  Hopefully it will have an associated citation soon...

**Comment by dkoes** [comment]
Also, I found the rfscore/nnscore data for MUV (I thought @Jsunseri  had it, but she corrected me).
http://bits.csb.pitt.edu/files/rfnn_muv_scores.tgz

**Comment by Jsunseri** [comment]
Well, actually we _both_ have it, but only one of us had access to the location... Results on DUD-E using the new default gnina CNN can be found at http://bits.csb.pitt.edu/files/defaultCNN_dude.tar.gz

**Comment by agamemnonc** [comment]
Thank you so much both. 

@Jsunseri if you are also happy to share with us the GNINA CNN results on LIT-PCBA, we can also include these in our benchmark -- we are also planning to run screening on LIT-PCBA.

And yes, please do let me know once your most recent paper has been published so that we can properly cite it.

**Comment by Jsunseri** [comment]
Sure thing, results on LIT-PCBA at http://bits.csb.pitt.edu/files/defaultCNN_litpcba.tar.gz

**Comment by agamemnonc** [comment]
Much appreciated @Jsunseri!
